### PR TITLE
Flask support

### PR DESCRIPTION
**Pull request by ifoukarakis**
Hi,

I'd like to suggest adding Flask support. This PR contains:

- [x] A plugin that creates Honeybadger payload from Flask's request object
- [x] A Flask extension that initializes Honeybadger using Flask's configuration object.
- [x] The Flask extension may be configured to automatically report any exceptions to honeybadger.

### CODE REVIEW

**Comment by ifoukarakis** [comment]
Seems there's an issue with Python 3.2. I will fix it.

**Comment by ifoukarakis** [comment]
Hi,

I finally fixed tests failing under Python3.2. When it comes to Python 3, [Flask requires python version > 3.2](http://flask.pocoo.org/docs/0.12/python3/#requirements). I had to disable the tests for python 3.2.

**Comment by joshuap** [comment]
@ifoukarakis thanks--will review and get back to you!

**Comment by emhoracek** [comment]
Hi! Is this likely to be merged? I would like to use it in a project!

**Comment by stympy** [comment]
Yup, sorry, this got lost in the shuffle... we'll work on getting this merged and released soon.

**Comment by emhoracek** [comment]
@stympy I just try using this branch on my project and it works great!

**Comment by stympy** [comment]
@emhoracek Awesome, thanks for the info!

**Comment by stympy** [comment]
@demsullivan What's the ETA on this?

**Comment by demsullivan** [comment]
Merged - a bit of housekeeping to do, and then will release a new version later today.

**Comment by demsullivan** [comment]
Hey @ifoukarakis - looks like the build failed after I merged it - perhaps something changed with Flask since you submitted the PR?

https://travis-ci.org/honeybadger-io/honeybadger-python/jobs/398354921

Any insights?

**Comment by ifoukarakis** [comment]
I'll have a look ASAP.

**Comment by ifoukarakis** [comment]
Created https://github.com/honeybadger-io/honeybadger-python/pull/30 to fix this.

**Pull request merged**
