### PR TITLE
Add user name to session object

### PR DESCRIPTION
**Pull request by dotysan**
Make it easy to track down what user got the error.

### CODE REVIEW

**Review by subzero10 — COMMENTED** [review]
This looks good, but I would like to hear from @joshuap or @stympy:
- Where would this information show in the error page?

So far, I've known that we use _context_ to set information such as _username_.

**Comment by stympy** [comment]
> * Where would this information show in the error page?

It would appear in the session block on the error page, along with the other session data.

> So far, I've known that we use _context_ to set information such as _username_.

Yes, the context is the place for this kind of info. This is what we do with the Ruby client:

https://github.com/honeybadger-io/honeybadger-ruby/blob/72ab159a03101cd459df9959895e5a17387c1970/lib/honeybadger/plugins/warden.rb#L13

**Comment by subzero10** [comment]
Following @stympy's advice, I think we should go for this solution #156. What do you think @dotysan?

**Comment by subzero10** [comment]
This is handled with #156, which was just published ([0.16.0](https://pypi.org/project/honeybadger/0.16.0/))!

**Comment by joshuap** [comment]
@subzero10 do you know if there is a user ID attribute available? It would be good to add `user_id` to the context, since that's one of the special keys we use for advanced features:

image

**Comment by stympy** [comment]
@joshuap we also added username as one of those special keys (in addition to user_id and user_email) to Honeybadger's processing, as a result of this change 😉

**Comment by subzero10** [comment]
> do you know if there is a user ID attribute available?

@joshuap I couldn't find anything official but I can read from SO that people can get a user id from the User object.
I added it!

**Comment by dotysan** [comment]
I jus got a backtrace in Django with 0.20.1 and it is missing the user name again. :-(

**Comment by joshuap** [comment]
@subzero10 @Kelvin4664 can you take a look at this?

**Comment by subzero10** [comment]
Yes, I've made a note to try and reproduce in the coming days.

**Comment by subzero10** [comment]
Hey @dotysan, thanks for reporting the issue! I've found the problem and submitted #176.

**Comment by subzero10** [comment]
@dotysan, I just published `0.20.2`. This version should propertly report user name and id now!

**Comment by dotysan** [comment]
@subzero10 Thx! I did have honeybadger middleware at the top, but still didn't get the user name.

Will test with 0.20.2 again now.

**Comment by subzero10** [comment]
> I did have honeybadger middleware at the top, but still didn't get the user name.

This makes sense, considering the fix we just published. With `0.20.2`, it should work!

**Comment by dotysan** [comment]
Yay! 
image

**Comment by subzero10** [comment]
I'm glad it worked for you this time! And thank you for helping me with the fix :)

**Pull request closed without merging**
