### PR TITLE
Remove deepcopy

### LINKED ISSUE #172: Cannot pickle TextIOWrapper
I inherited a Django app with very poor code quality and wanted to at least get some logging setup on it. I'm mostly a Rails developer so I'm a little out of my depths. I'm getting an error "can't pickle '_io.TextIOWrapper' object". 

I did spin up the test Django app from this repo and I am getting the same error there too, even after setting up and venv for it. Trace below if that helps:

```
Traceback (most recent call last):
  File "/.../honeybadger-python/examples/django_app/vevn/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/.../honeybadger-python/examples/django_app/vevn/lib/python3.11/site-packages/django/core/handlers/base.py", line 199, in _get_response
    response = self.process_exception_by_middleware(e, request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../honeybadger-python/examples/django_app/vevn/lib/python3.11/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
    response = middleware_method(request, exception)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../honeybadger-python/examples/django_app/vevn/lib/python3.11/site-packages/honeybadger/contrib/django.py", line 129, in process_exception
    honeybadger.notify(exception)
  File "/.../honeybadger-python/examples/django_app/vevn/lib/python3.11/site-packages/honeybadger/core.py", line 64, in notify
    return self._send_notice(exception, context=merged_context, fingerprint=fingerprint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../honeybadger-python/examples/django_app/vevn/lib/python3.11/site-packages/honeybadger/core.py", line 24, in _send_notice
    payload = create_payload(exception, exc_traceback, config=self.config, context=context, fingerprint=fingerprint)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../honeybadger-python/examples/django_app/vevn/lib/python3.11/site-packages/honeybadger/payload.py", line 144, in create_payload
    return default_plugin_manager.generate_payload(payload, config, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../honeybadger-python/examples/django_app/vevn/lib/python3.11/site-packages/honeybadger/plugins.py", line 75, in generate_payload
    default_payload = plugin.generate_payload(default_payload, config, context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../honeybadger-python/examples/django_app/vevn/lib/python3.11/site-packages/honeybadger/contrib/django.py", line 84, in generate_payload
    'cgi_data': filter_dict(request.META, config.params_filters),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../honeybadger-python/examples/django_app/vevn/lib/python3.11/site-packages/honeybadger/utils.py", line 18, in filter_dict
    data_copy = copy.deepcopy(data)
                ^^^^^^^^^^^^^^^^^^^
  File "/.../.asdf/installs/python/3.11.5/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/.../.asdf/installs/python/3.11.5/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/.../.asdf/installs/python/3.11.5/lib/python3.11/copy.py", line 161, in deepcopy
    rv = reductor(4)

### PR DESCRIPTION
**Pull request by stympy**
Fixes #172

### CODE REVIEW

**Review by joshuap — APPROVED** [review]
I'm lacking context on the substance of this change tbh, so it would be nice if @Kelvin4664 or @subzero10 could also review.

**Comment by Kelvin4664** [comment]
@joshuap We added deepcopy to fix #165, which is a far less critical bug than this one.
I think it makes sense to remove since that bug was a user error and we were only trying to make the system fail safe.

**Comment by Kelvin4664** [comment]
Also, i believe directly reverting that PR will be a better approach here. I have opened #174 for that. Someone take a look before i merge.

**Comment by stympy** [comment]
I think it makes sense to keep the removal of keys that are tuples, but the way that it was done could be improved (this PR), so I'm going to go with this to fix the issue, and we can revisit if necessary.

**Comment by subzero10** [comment]
> I think it makes sense to keep the removal of keys that are tuples

+1

**Pull request merged**
