### PR TITLE
Merge plugins

### PR DESCRIPTION
**Pull request by Kelvin4664**
#77 
- Combine payload generated byall registered plugins
- updated a few corresponding test cases

#79 
-Catch attribute error when initialising handler for latest lambda runtime

### CODE REVIEW

**Review by joshuap — COMMENTED** [review]
Looking good @Kelvin4664. Does the Flask plugin need to be updated as well?

**Comment by Kelvin4664** [comment]
Yes.... My bad! 
I missed that bit.
Adding now...

**Review by joshuap — APPROVED** [review]
LGTM, thanks 👍

**Comment by joshuap** [comment]
Feel free to merge and update #79 to let kpavlovsky know that it's ready to test

**Pull request merged**
